# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pesquisar_new.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow5(object):
    def setup5(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(793, 321)
        MainWindow.setStyleSheet("font: 14pt \"Microsoft JhengHei UI\";")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.nome_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.nome_comboBox.setAutoFillBackground(False)
        self.nome_comboBox.setEditable(True)
        self.nome_comboBox.setObjectName("nome_comboBox")
        self.gridLayout_2.addWidget(self.nome_comboBox, 0, 2, 1, 1)
        self.max_dateTimeEdit = QtWidgets.QDateTimeEdit(self.centralwidget)
        self.max_dateTimeEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2019, 7, 1), QtCore.QTime(0, 0, 0)))
        self.max_dateTimeEdit.setDate(QtCore.QDate(2019, 7, 1))
        self.max_dateTimeEdit.setMaximumDateTime(QtCore.QDateTime(QtCore.QDate(9999, 12, 31), QtCore.QTime(23, 59, 59)))
        self.max_dateTimeEdit.setCalendarPopup(True)
        self.max_dateTimeEdit.setObjectName("max_dateTimeEdit")
        self.gridLayout_2.addWidget(self.max_dateTimeEdit, 6, 4, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setStyleSheet("font: 6pt \"MS Shell Dlg 2\";")
        self.label_6.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 3, 4, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setStyleSheet("font: 6pt \"MS Shell Dlg 2\";")
        self.label_5.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 3, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem, 5, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setStyleSheet("font: 6pt \"MS Shell Dlg 2\";")
        self.label_7.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 5, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setStyleSheet("font: 6pt \"MS Shell Dlg 2\";")
        self.label_8.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 5, 4, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem1, 1, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem2, 3, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 4, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 2, 0, 1, 1)
        self.marca_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.marca_comboBox.setEditable(True)
        self.marca_comboBox.setObjectName("marca_comboBox")
        self.gridLayout_2.addWidget(self.marca_comboBox, 2, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 25, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem3, 7, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 6, 0, 1, 1)
        self.max_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.max_doubleSpinBox.setEnabled(True)
        self.max_doubleSpinBox.setWrapping(False)
        self.max_doubleSpinBox.setFrame(True)
        self.max_doubleSpinBox.setPrefix("")
        self.max_doubleSpinBox.setObjectName("max_doubleSpinBox")
        self.gridLayout_2.addWidget(self.max_doubleSpinBox, 4, 4, 1, 1)
        self.min_dateTimeEdit = QtWidgets.QDateTimeEdit(self.centralwidget)
        self.min_dateTimeEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2019, 5, 1), QtCore.QTime(0, 0, 0)))
        self.min_dateTimeEdit.setCalendarPopup(True)
        self.min_dateTimeEdit.setObjectName("min_dateTimeEdit")
        self.gridLayout_2.addWidget(self.min_dateTimeEdit, 6, 2, 1, 1)
        self.preco_checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.preco_checkBox.setEnabled(True)
        self.preco_checkBox.setTristate(False)
        self.preco_checkBox.setObjectName("preco_checkBox")
        self.gridLayout_2.addWidget(self.preco_checkBox, 4, 5, 1, 1)
        self.data_checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.data_checkBox.setObjectName("data_checkBox")
        self.gridLayout_2.addWidget(self.data_checkBox, 6, 5, 1, 1)
        self.min_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.min_doubleSpinBox.setObjectName("min_doubleSpinBox")
        self.gridLayout_2.addWidget(self.min_doubleSpinBox, 4, 2, 1, 1)
        self.cancelar_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.cancelar_pushButton.setObjectName("cancelar_pushButton")
        self.gridLayout_2.addWidget(self.cancelar_pushButton, 8, 4, 1, 1)
        self.pesquisar_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pesquisar_pushButton.setObjectName("pesquisar_pushButton")
        self.gridLayout_2.addWidget(self.pesquisar_pushButton, 8, 2, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Janela de Pesquisa"))
        self.max_dateTimeEdit.setDisplayFormat(_translate("MainWindow", "dd-MM-yyyy HH:00"))
        self.label_6.setText(_translate("MainWindow", "MAX:"))
        self.label_5.setText(_translate("MainWindow", "MIN:"))
        self.label_7.setText(_translate("MainWindow", "MIN:"))
        self.label_8.setText(_translate("MainWindow", "MAX:"))
        self.label.setText(_translate("MainWindow", "Nome:"))
        self.label_3.setText(_translate("MainWindow", "Preço:"))
        self.label_2.setText(_translate("MainWindow", "Marca:"))
        self.label_4.setText(_translate("MainWindow", "Data Scrap:"))
        self.min_dateTimeEdit.setDisplayFormat(_translate("MainWindow", "dd-MM-yyyy HH:mm"))
        self.preco_checkBox.setText(_translate("MainWindow", "Definir um preço"))
        self.data_checkBox.setText(_translate("MainWindow", "Definir uma data"))
        self.cancelar_pushButton.setText(_translate("MainWindow", "Cancelar"))
        self.pesquisar_pushButton.setText(_translate("MainWindow", "Pesquisar"))

