# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'projecto4.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!
from ui.adicionar import *
from ui.modificar import *
from ui.pesquisar import *
from ui.mostrar_imagem import *
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def mostar_imagem(self):
        self.window = QtWidgets.QMainWindow()
        self.ui6 = Ui_MainWindow6()
        self.ui6.setup6(self.window)
        self.window.show()
    def pesquisar(self):
        self.window = QtWidgets.QMainWindow()
        self.ui5 = Ui_MainWindow5()
        self.ui5.setup5(self.window)
        self.window.show()
    def remover(self):
        self.window = QtWidgets.QMainWindow()
        self.ui3 = Ui_MainWindow3()
        self.ui3.setup3(self.window)
        self.window.show()
    def adicionar(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow2()
        self.ui.setup(self.window)
        self.window.show()
    def modificar(self):
        self.window = QtWidgets.QMainWindow()
        self.ui4 = Ui_MainWindow4()
        self.ui4.setup4(self.window)
        self.window.show()
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(998, 775)
        MainWindow.setStyleSheet("font: 63 12pt \"Segoe UI Semibold\";")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(16777215, 150))
        self.label.setBaseSize(QtCore.QSize(0, 0))
        self.label.setLineWidth(1)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("./Imagens/Imagem1.png"))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(False)
        self.label.setIndent(-1)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.search_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.search_pushButton.setMinimumSize(QtCore.QSize(0, 20))
        self.search_pushButton.setMaximumSize(QtCore.QSize(200, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./Imagens/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.search_pushButton.setIcon(icon)
        self.search_pushButton.setObjectName("search_pushButton")
        self.horizontalLayout_3.addWidget(self.search_pushButton)
        self.reset_pushButton = QtWidgets.QPushButton(self.centralwidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("./Imagens/002-update-arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.reset_pushButton.setIcon(icon1)
        self.reset_pushButton.setObjectName("reset_pushButton")
        self.horizontalLayout_3.addWidget(self.reset_pushButton)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.importar_pushButton = QtWidgets.QPushButton(self.centralwidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("./Imagens/001-import.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.importar_pushButton.setIcon(icon2)
        self.importar_pushButton.setObjectName("importar_pushButton")
        self.horizontalLayout_3.addWidget(self.importar_pushButton)
        self.exportar_pushButton = QtWidgets.QPushButton(self.centralwidget)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("./Imagens/003-package.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exportar_pushButton.setIcon(icon3)
        self.exportar_pushButton.setObjectName("exportar_pushButton")
        self.horizontalLayout_3.addWidget(self.exportar_pushButton)
        spacerItem = QtWidgets.QSpacerItem(5, 5, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.add_pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("./Imagens/001-plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_pushButton_2.setIcon(icon4)
        self.add_pushButton_2.setAutoDefault(False)
        self.add_pushButton_2.setDefault(False)
        self.add_pushButton_2.setObjectName("add_pushButton_2")
        self.horizontalLayout_3.addWidget(self.add_pushButton_2)
        self.modify_pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("./Imagens/004-reload.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.modify_pushButton_3.setIcon(icon5)
        self.modify_pushButton_3.setObjectName("modify_pushButton_3")
        self.horizontalLayout_3.addWidget(self.modify_pushButton_3)
        self.remove_pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("./Imagens/008-trash.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.remove_pushButton_4.setIcon(icon6)
        self.remove_pushButton_4.setObjectName("remove_pushButton_4")
        self.horizontalLayout_3.addWidget(self.remove_pushButton_4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.treeWidget = QtWidgets.QTreeWidget(self.centralwidget)
        self.treeWidget.setLineWidth(1)
        self.treeWidget.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked)
        self.treeWidget.setUniformRowHeights(False)
        self.treeWidget.setColumnCount(6)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(0, "ID")
        self.treeWidget.headerItem().setText(1, "Nome")
        self.treeWidget.headerItem().setText(2, "Marca")
        self.treeWidget.headerItem().setText(3, "Preço")
        self.treeWidget.header().setDefaultSectionSize(160)
        self.treeWidget.header().setMinimumSectionSize(37)
        self.verticalLayout_3.addWidget(self.treeWidget)
        self.gridLayout.addLayout(self.verticalLayout_3, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Janela Principal"))
        self.search_pushButton.setText(_translate("MainWindow", "Pesquisar Artigos"))
        self.reset_pushButton.setText(_translate("MainWindow", "Reset"))
        self.importar_pushButton.setText(_translate("MainWindow", "Importar"))
        self.exportar_pushButton.setText(_translate("MainWindow", "Exportar"))
        self.add_pushButton_2.setText(_translate("MainWindow", "Adicionar"))
        self.modify_pushButton_3.setText(_translate("MainWindow", "Modificar"))
        self.remove_pushButton_4.setText(_translate("MainWindow", "Remover"))
        self.treeWidget.headerItem().setText(4, _translate("MainWindow", "Data Scrap"))
        self.treeWidget.headerItem().setText(5, _translate("MainWindow", "Imagem"))

